### ISSUE TITLE
USER STORY:

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Basty-Shops-Ecommerce-Code-Institute-Project#12]
# User Story 

In order to select products to purchase, as a **user**, i want to see a list f products 

## Acceptance criteria:

- Products rendered on cards
- Cards contain product image, title, product name and price
- 3 products per row on Desktop screens
- 2 products per row on tablets and mobile screens

### Tasks

- [x] Design layout page
- [x] Design layout product cards
- [x] Create HTML and CSS code
- [x] Fully responsive
