### ISSUE TITLE
USER STORY: Home page (2nd section)

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Basty-Shops-Ecommerce-Code-Institute-Project#3]
# User Story 

In order to provide value content, as a **developer**, i can create a categories setion with nice pictures , and a carousel of new products for the new season

## Acceptance criteria:

- 3 columns  layout for categories images
-  Images linked to category page
-  Carousel of new seasson products

### Tasks

- [x] Design layout
- [x]  Design and choose type of products carousel
- [x] Choose categories images
- [x]  Create HTML and CSS code
- [x] Fully responsive
