### ISSUE TITLE
USER STORY: Home page (3th section)

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Basty-Shops-Ecommerce-Code-Institute-Project#4]
# User Story 

In order to provide value content, as a **deveoper**, i can provide value information about shipping, returns and subscriptions

## Acceptance criteria:

- 3 columns layout:
     1.Shipping
     2. Returns
     3. Subscriptions(add call to action button)
- Elements must be over 300px height and width
- Background images if possible or nice icons instead

### Tasks

- [x] Design layout
- [x] Choose images or icones
- [x] Create content with value information in each element
- [x] Create HTML and CSS code
- [x] Fully responsive
